---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  labels: {{labels}}
{% if storage_class is defined %}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{storage_class}}
{% endif %}
spec:
  accessModes: {{accessModes}}
  resources:
    requests:
      storage: "{{storage}}"
