---
apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  labels:
    k8s-app: logstash
    version: v1
spec:
  template:
    metadata:
      labels:
        k8s-app: logstash
        version: v1

    spec:
      containers:
        - name: logstash
          image: {{image}}
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
          command:
            - logstash
            - -f
            - /etc/logstash/conf.d
            - -r
          volumeMounts:
            - mountPath: /etc/logstash/conf.d
              name: logstashconf

            - mountPath: /var/log/journal
              name: varlogjournal

            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers

            - mountPath: /var/log/containers
              name: varlogcontainers

      volumes:
        - {{logstash_conf_volume}}
        - name: varlogjournal
          hostPath:
            path: /var/log/journal

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
