---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-controller
  labels:
    controller: alertmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        controller: alertmanager
    spec:
      containers:
       - name: alertmanager-controller
         image: {{alertmanager_image}}
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 100Mi
