apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: {{svc_type}}
  ports:
  - name: web
    port: 3000
    protocol: TCP
{% if svc_type != "ClusterIP" %}
    nodePort: {{node_port}}
{% endif %}
  selector:
    app: grafana
